import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import ModernNavbar from "@/components/navbar/navbar";
import { AnnouncementBar } from "@/components/annoucement-bar/AnnoucementBar";

// ✅ Load Plus Jakarta Sans
const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Adjust weights as needed
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakarta.variable}>
      <body className="font-sans antialiased">
        <AnnouncementBar text="Latest update: Keizer Group announces upcoming launch of sustainable energy solutions in West Africa." />

        <ModernNavbar />
        {children}
      </body>
    </html>
  );
}
